name: Deploy to GitHub Pages (Simplified)

on:

  pull_request:
    branches: [ master, release ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Show environment
        run: |
          echo "=== ENVIRONMENT INFO ==="
          echo "Current directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Directory contents:"
          ls -la
          echo "========================="
          
      - name: Install dependencies
        run: npm ci
        
      - name: Show dependencies
        run: |
          echo "=== DEPENDENCIES INFO ==="
          echo "Node modules:"
          ls -la node_modules/.bin/ | grep webpack
          echo "Package.json scripts:"
          cat package.json | grep -A 10 '"scripts"'
          echo "========================="
          
      - name: Try simple webpack build
        run: |
          echo "=== SIMPLE WEBPACK BUILD ==="
          echo "Running: npx webpack --config webpack.simple.js"
          npx webpack --config webpack.simple.js
          echo "Build exit code: $?"
          echo "Directory contents after build:"
          ls -la
          echo "========================="
          
      - name: Create dist directory if missing
        run: |
          echo "=== ENSURING DIST DIRECTORY ==="
          if [ ! -d "dist" ]; then
            echo "❌ dist directory not found, creating it manually..."
            mkdir -p dist
            echo "✅ Created dist directory"
          else
            echo "✅ dist directory exists"
          fi
          
          echo "Creating minimal content..."
          echo '<!DOCTYPE html><html><head><title>RAGtional</title></head><body><h1>RAGtional Landing Page</h1><p>Build in progress...</p></body></html>' > dist/index.html
          echo "Created index.html"
          
          touch dist/.nojekyll
          echo "Created .nojekyll"
          
          echo "Final dist contents:"
          ls -la dist/
          echo "========================="
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          single-commit: true
          commit-message: "Deploy RAGtional Landing Page - ${{ github.sha }}"
          token: ${{ secrets.GITHUB_TOKEN }}
